---
title: "README"
author: "Bernie"
date: "7/6/2020"
output: html_document
---

##GettingCleaningDataCourseProject Repository ReadMe

This repository was created for the final assignment of the JHU Getting and Cleaning Data course.

The following documents are contianed within this repo:
    * run_analysis.R
    * CodeBook.Rmd
    * CodeBook.html
    * README.rmd (this document)

###run_analysis.R
This R script performs the analysis required by the assignment.  Running this script downloads additional files to the working directory that are necessary to carrying out the process of "Tidying" data.  Specifically, the script downloads a zip file (UCI HAR Dataset.zip) containing data obtained by measuring 30 subjects performing 6 activities while wearing a waiste-mounted Samsun Galexy II smart phone with embedded accelerometer and gyroscope sensors.  The data collection was conducted in two phases, "test" and "train".  The script unzips the folder and then imports data from several space-delimited text files:
    * activity_labels.txt - A table of meaningful activity descriptions and their index which corresponds to values in other data files
    * features.txt - A table of features, or measurements, that are contained in the data files.  Each feature has an index that corresponds to the column number of the data file
    * features_info.txt - Details about each of the features and how they were calculated
    * README.txt - Information about the conduct of the test and the creation of the test data.
    * test directory
    * train directory
    
The test and train directory both include the collected test data:
    * subject_test - An array of subject ID's corresponding to each test subject for each row of data
    * X_test.txt - A matrix of test data recorded by the sensors and processed by the test engineers.  Each column corresponds to a feature and each row an observation.
    * Y-test.txt - An array of activity ID's corresponding to the indicies in the activity_labels.txt file
    
This R script then concatenates these separate datasets into a tidy dataset, adds meaningful variable names and activity ID strings, calculates the average of each feature grouped by activity and subject, and prints the results to a text file:
    * avgDataTable.txt
    
###CodeBook.Rmd, CodeBook.html
This R-Markdown file explains the process carried out by run_analysis.R in chunks.  Additionally, it prints a summary table of the variables contained in the tidy datasets to include variable descriptions and units.  This R Markdown file was knit and the resulting html document was also included in the repository.  The file should be viewed in an internet browser.